version: "3"
services:
  flask-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGO_DBNAME=project2
      - MONGO_URI=mongodb://csh7916:pwd@mongodb:27017
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_PORT=3000
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=csh7916
      - MONGO_INITDB_ROOT_PASSWORD=pwd
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: