name: log github events
on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, closed]
    branches: [main, master]
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      COMMIT_LOG_API: ${{ secrets.COMMIT_LOG_API }}
      GITHUB_LOGIN: ${{ github.actor }}
      COMMITS: ${{ toJSON(github.event.commits) }}
      REPOSITORY_URL: ${{ github.repository_url }}
      EVENT_TYPE: ${{ github.event_name }}
      EVENT_ACTION: ${{ github.event.action }}
      PR_MERGED: ${{ github.event.pull_request.merged }}
      PR_CREATED_AT: ${{ github.event.pull_request.created_at }}
      PR_CLOSED_AT: ${{ github.event.pull_request.closed_at }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv --python $(which python)
          pipenv install pytz
          pipenv install python-dateutil
          pipenv install build
          pipenv install requests
          pipenv install gitcommitlogger
      - name: Debug Environment Variables
        run: |
          echo "REPOSITORY_URL: $REPOSITORY_URL"
          echo "EVENT_TYPE: $EVENT_TYPE"
          echo "EVENT_ACTION: $EVENT_ACTION"
          echo "GITHUB_LOGIN: $GITHUB_LOGIN"
          if [ -z "$COMMIT_LOG_API" ]; then
            echo "COMMIT_LOG_API is not set"
          else
            echo "COMMIT_LOG_API is set"
          fi
      - name: Log pull request opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened' && secrets.COMMIT_LOG_API
        run: |
          pipenv run gitcommitlogger -r "$REPOSITORY_URL" -t pull_request_opened -d "$PR_CREATED_AT" -un "$GITHUB_LOGIN" -o commit_stats.csv -u "$COMMIT_LOG_API" -v
      - name: Log pull request closed and merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && secrets.COMMIT_LOG_API
        run: |
          echo "$COMMITS" > commits.json
          cat commits.json # debugging
          pipenv run gitcommitlogger -r "$REPOSITORY_URL" -t pull_request_merged -d "$PR_CLOSED_AT" -un "$GITHUB_LOGIN" -i commits.json -o commit_stats.csv -u "$COMMIT_LOG_API" -v
      - name: Log pull request closed without merge
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false && secrets.COMMIT_LOG_API
        run: |
          pipenv run gitcommitlogger -r "$REPOSITORY_URL" -t pull_request_closed -d "$PR_CLOSED_AT" -un "$GITHUB_LOGIN" -o commit_stats.csv -u "$COMMIT_LOG_API" -v
      - name: Log push
        if: github.event_name == 'push' && secrets.COMMIT_LOG_API
        run: |
          echo "$COMMITS" > commits.json
          cat commits.json # debugging
          pipenv run gitcommitlogger -r "$REPOSITORY_URL" -t "$EVENT_TYPE" -i commits.json -o commit_stats.csv -u "$COMMIT_LOG_API" -v
